apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -stage
namespace: app-stage

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml
  - path: patch-resources.yaml

images:
  - name: ghcr.io/ajdevopssolutions/nodejs-docker-k8s-starter
    newName: ghcr.io/ajdevopssolutions/nodejs-docker-k8s-starter
    newTag: stage

configMapGenerator:
  - name: nodeapp-config
    behavior: merge
    literals:
      - MESSAGE=Hello from STAGE 🚀
