# Default values for nodeapp.

namespaceOverride: "" # set to non-empty to install resources into this namespace explicitly

replicaCount: 2

image:
  repository: ghcr.io/ajdevopssolutions/nodejs-docker-k8s-starter
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: [] # e.g., [{ name: regcred }]

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # runAsNonRoot: true
  # runAsUser: 10001

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: nodeapp.local
      paths:
        - path: /?(.*)
          pathType: Prefix
  tls: []
  #  - secretName: nodeapp-tls
  #    hosts:
  #      - nodeapp.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env:
  PORT: "3000"
  MESSAGE: "Hello from ConfigMap 👋"

readinessProbe:
  path: /healthz
  initialDelaySeconds: 3
  periodSeconds: 5

livenessProbe:
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10
