# values-prod.yaml
replicaCount: 3

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nodeapp.example.com
      paths:
        - path: /?(.*)
          pathType: Prefix
  tls:
    - secretName: nodeapp-tls
      hosts:
        - nodeapp.example.com

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 1
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

env:
  MESSAGE: "Hello from PROD 🔐"
